Charles development
chuckluv/Step pull request #3
Opened 2020-05-28 21:12 UTC by chuckluv

2020-05-28 23:48 UTC, bsidhom requested changes

2020-05-28 23:48 UTC, bsidhom commented on portfolio/src/main/webapp/index.html
> +      <p>This Portfolio contians my life growing up and during college. Hope you enjoy learning a little bit about me.</p>
"contians" -> "contains"

2020-05-28 23:48 UTC, bsidhom commented on portfolio/src/main/webapp/script.js
> +      ['Favorite TV show is Game of Thrones', 'Favorite Sport is Football', 'I have fractured every finger on my left hand', 'I have played the double bass since Third Grade'];
Ouch! Sorry to hear about your left hand!

2020-05-28 23:48 UTC, bsidhom commented on portfolio/src/main/webapp/script.js
> +  const factContainer = document.getElementById('greeting-container');
You may want to change the name of this containing element (maybe 'fun-fact-container' or similar).

2020-05-28 23:54 UTC, KoopaKing requested changes
A few more changes, you can keep them in this pull request I think by adding additional commits into it, or updating the commits included in the change (maybe squashing the fixes into the existing commits).

Also high level comments:
 - you might want to add some content to your new HTML files, even just a TODO or WIP comment
 - you might want to remove one of the duplicate pictures (Collegelife) since it seems like you will probably only use one

Let me know if you want help updating the pull request or squashing the commits.

2020-05-28 23:54 UTC, KoopaKing commented on portfolio/src/main/webapp/index.html
> +table, th, td {
You can probably put this in your style.css

2020-05-28 23:54 UTC, KoopaKing commented on portfolio/src/main/webapp/index.html
> +    <div id='choice' >
Please use double quotes for attribute values per the [Google style guide](https://google.github.io/styleguide/htmlcssguide.html#HTML_Quotation_Marks).

2020-05-28 23:54 UTC, KoopaKing commented on portfolio/src/main/webapp/script.js
> +      ['Favorite TV show is Game of Thrones', 'Favorite Sport is Football', 'I have fractured every finger on my left hand', 'I have played the double bass since Third Grade'];
You might reformat this so the line isn't long. Google javascript style guide (and most Google style guides) recommend [80 char max limit](https://google.github.io/styleguide/jsguide.html#formatting-column-limit) per line unless there is a functional reason not to break it.

2020-05-29 19:34 UTC, KoopaKing commented on portfolio/src/main/webapp/style.css
> +
super nit: there is a lot of unnecessary whitespace.

2020-05-29 19:35 UTC, KoopaKing commented on portfolio/src/main/webapp/college.html
> +#conclude with start of STEP intern ship-->
This newline thing is super annoying. No need to fix now though. This isn't blocking.

2020-05-29 19:35 UTC, KoopaKing approved these changes

2020-06-01 16:33 UTC, KoopaKing reviewed
So this is great, I love the amount of content you got done.

Can you clean up the whitespace and formatting in a single commit though before merging?

2020-06-01 16:33 UTC, KoopaKing commented on portfolio/src/main/webapp/college.html
> +<h2>Profession Times</h2>
Not sure why the indentation changes suddenly here.

2020-06-01 16:33 UTC, KoopaKing commented on portfolio/src/main/webapp/college.html
> +
Can you clean up the whitespace in this file a bit?

2020-06-01 16:33 UTC, KoopaKing commented on portfolio/src/main/webapp/growing-up.html
> +                in hold in the picture at my house.</p>
should this start with "I'm holding"?

2020-06-01 16:33 UTC, KoopaKing commented on portfolio/src/main/webapp/style.css
> +
whitespace issue again.

2020-06-01 16:33 UTC, KoopaKing commented on portfolio/src/main/webapp/growing-up.html
> +
whitespace issue again.

2020-06-01 16:33 UTC, KoopaKing commented on portfolio/src/main/webapp/growing-up.html
> +</html>
no EOF.

2020-06-01 16:33 UTC, KoopaKing commented on portfolio/src/main/webapp/college.html
> +</html>
no EOF

2020-06-01 19:00 UTC, bsidhom approved these changes
LGTM

2020-06-01 19:08 UTC, merged