add comment feature to webiste
chuckluv/Step pull request #4
Opened 2020-06-03 15:46 UTC by chuckluv

2020-06-04 06:16 UTC, KoopaKing requested changes
/formatter-meme

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/data/Post.java
> +public final class Post{
Did you run this through the formatter? You're missing a space before the bracket.

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/data/Post.java
> +}
newline for EOF

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +
Trailing whitespace? gross.

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  String userComment = request.getParameter("comment");
Might be nice to do some validation here.

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  //comments.add(userComment);
remove this.

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
>  @WebServlet("/data")
should this be a different path, like say /comments or something?

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +      Query query = new Query("Comments").addSort("timestamp", SortDirection.DESCENDING);
You're using a bunch of magic strings. Please refactor them.

Also by this I mean your code depends on the spelling of "Comments", "timestamp", and "comment" all matching.

it would be better to have something like:
```java
  private static final String COMMENTS_ENTITY_NAME = "Comments";
  private static final String TIMESTAMP_PROPERTY_KEY = "timestamp";
  private static final String COMMENT_PROPERTY_KEY = "comment";
```

then use those constants in both places.

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +   response.sendRedirect("/index.html");
Did they tell you to put the redirect in the rest API response? That's pretty strange for a successful response.

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/webapp/script.js
> +  //console.log(JSON.stringify(com.comments))
remove this before merging please.

2020-06-04 06:16 UTC, KoopaKing commented on portfolio/src/main/webapp/script.js
> +    fetch('/data').then(response => response.json()).then((com) => {
how about `comments` instead of `com`?

2020-06-04 20:24 UTC, chuckluv commented
http://charleslovett-step-2020.appspot.com/
This is the url for the webpage so you can look at it

2020-06-04 22:39 UTC, KoopaKing approved these changes
Seems ok to merge, but try to address the comments first.

2020-06-04 22:39 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    String userComment = request.getParameter(COMMENT_PROPERTY_KEY);
This is not the `COMMENT_PROPERTY_KEY`... It happens to have the same value, but it's not the same. One is a storage layer concept, one is a user-facing API concept. This is something more like `COMMENT_REQUEST_PARAMETER_KEY`.

2020-06-04 22:39 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
>      for (Entity entity : results.asIterable()) {
I think you can put the limit here... Something like:
```java
FetchOptions fetchOptions = FetchOptions.Builder.withLimit(max);
for (Entity entity : results.asIterable(fetchOptions)) {
   ...
```

Then you wont need to do this whole count check thing...

2020-06-04 22:39 UTC, KoopaKing commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    String maxString = request.getParameter("maxnum");
What is this `maxnum` thing? Or just as importantly, why does it exist?

Also, without that, some of the below code doesn't make sense.

2020-06-05 19:01 UTC, bsidhom approved these changes
Not blocking merge on any of these comments (some are nits), but I think we should at least talk about error handling and what we expect to happen in edge cases.

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +import java.util.*;
Please explicitly import just the classes you use. This makes it easier to tell at a glance where different classes come from and what your dependencies are.

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  private int max=5;
A more descriptive name will aid readability here, e.g., `maxResultsPerQuery` (or whatever makes sense to you).

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    PreparedQuery results = datastore.prepare(query);
Javadoc comments say that this specifically does not use a transaction. Is that safe here? What happens if somebody else adds a comment as we're listing them here? (Note: I don't know the answer to this, just asking whether you've investigated.)

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +      long timestamp = (long) entity.getProperty(TIMESTAMP_PROPERTY_KEY);
Is it worth checking that this property exists and checking that it's the correct type before trying to cast?

I'm not sure how AppEngine translates inline exceptions (e.g., NullPointerExceptions) to responses (500s?).

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    } else if (maxString != null) {
Can a user specify _both_ a comment and a max number of comments in the same request?

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        System.out.println("Could not convert to int: " + maxString);
Note: this generates a local system (AppEngine) log and swallows the exception. Do you want to surface this error to the user in any way?

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    Gson gson = new Gson();
According to the [javadoc](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/Gson.html), this class is thread-safe. You could store a Gson instance in the constructor and reuse it across requests. This is especially helpful if you end up adding configuration options and using Gson in multiple places.

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/webapp/script.js
> +function createTaskElement(comment) {
This could use a more descriptive name (`createCommentElement`?).

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/webapp/script.js
> +function deleteTask(task) {
Looks like this is only used for comments right now. If there are plans to extend this and make it work with arbitrary "tasks", this name might make sense. Otherwise, consider renaming to `deleteComment` or similar.

2020-06-05 19:01 UTC, bsidhom commented on portfolio/src/main/java/com/google/sps/servlets/DeleteServlet.java
> +    datastore.delete(taskEntityKey);
It looks like this [throws an exception](https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/datastore/DatastoreService.html#delete-com.google.appengine.api.datastore.Key...-) if the given key is invalid. I assume that non-existent (e.g., already-deleted) keys are considered invalid. In that case, it's possible for legitimate requests from different users to result in `IllegalArgumentException`s.

As I mentioned above, I'm not sure how AppEngine handles uncaught exceptions, but you may want to consider at least catching exceptions and trying to return the appropriate response codes in that case (unless we'll be addressing that later).

2020-06-08 16:41 UTC, merged